name: Build NanoLimbo and upload jar to Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean shadowJar \
            -PUUID="${{ secrets.UUID }}" \
            -PANYTLS_PORT="${{ secrets.ANYTLS_PORT }}" \
            -PNAME="${{ secrets.NAME }}" \
            -PTUIC_PORT="${{ secrets.TUIC_PORT }}" \
            -PNEZHA_SERVER="${{ secrets.NEZHA_SERVER }}" \
            -PNEZHA_PORT="${{ secrets.NEZHA_PORT }}" \
            -PNEZHA_KEY="${{ secrets.NEZHA_KEY }}" \
            -PARGO_PORT="${{ secrets.ARGO_PORT }}" \
            -PARGO_DOMAIN="${{ secrets.ARGO_DOMAIN }}" \
            -PARGO_AUTH="${{ secrets.ARGO_AUTH }}" \
            -PS5_PORT="${{ secrets.S5_PORT }}" \
            -PHY2_PORT="${{ secrets.HY2_PORT }}" \
            -PREALITY_PORT="${{ secrets.REALITY_PORT }}" \
            -PANYREALITY_PORT="${{ secrets.ANYREALITY_PORT }}" \
            -PCFIP="${{ secrets.CFIP }}" \
            -PCFPORT="${{ secrets.CFPORT }}" \
            -PUPLOAD_URL="${{ secrets.UPLOAD_URL }}" \
            -PCHAT_ID="${{ secrets.CHAT_ID }}" \
            -PBOT_TOKEN="${{ secrets.BOT_TOKEN }}" \
            -PDISABLE_ARGO="${{ secrets.DISABLE_ARGO }}"

      - name: Prepare JAR
        id: prepare_jar
        run: |
          JAR_PATH=$(find build/libs -name "*.jar" ! -name "*sources*" ! -name "*javadoc*" | head -n 1)
          cp "$JAR_PATH" ./server.jar
          echo "JAR_SIZE=$(ls -lh ./server.jar | awk '{print $5}')" >> $GITHUB_OUTPUT

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: NanoLimbo-artifact
          path: server.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v7
        with:
          name: NanoLimbo-artifact

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "server.jar"
          tag: ${{ github.ref_name }}
          name: "NanoLimbo ${{ github.ref_name }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true
          body: "Automated release from workflow run #${{ github.run_number }}"
